[package]
name = "svg_gal"
version = "0.1.0"
# cargo edition
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.40.0"
svg = "0.15.1"